### ISSUE TITLE
rspec requires a relative path for using with Nitrous.io

### ISSUE THREAD

**Issue by fornof** [appacademy/prep-work#53]
https://github.com/appacademy/prep-work/tree/master/coding-test-2/practice-problems/spec
These files require a relative path to work, otherwise rspec cannot find the file. For instance: 
```
require '00_nearest_larger'
require 'rspec'
```
should be relative , so it should be 
```
require_relative '../lib/00_nearest_larger'
require 'rspec'
```
This is a minor thing, but it caught me off guard the first time I ran into that.

**Comment by rglassett** [comment]
The require statements work as-is for me using either `rake` or `bundle exec rspec`.
