### ISSUE TITLE
#15 - Discrete Logarithm Problem != medium difficulty

### ISSUE THREAD

**Issue by cbuchert** [appacademy/prep-work#67]
Who gets notified if I accidentally solve the discrete logarithm problem? I was told if I ever solved it I would either wake up very rich or very dead.

**Comment by rglassett** [comment]
Can you clarify? Problem 15 in the coding test 1 prep-work is `#is_prime?`, which is not a difficult problem.

**Comment by cbuchert** [comment]
Crap. Looks like the joke fell flat on that one. The discrete logarithm problem is the formula for finding primes without brute forcing.
